language: c++
sudo: true
dist: trusty
env: TRAVIS=1 XMIPP_NOSCIPION=True CCACHE_COMPILERCHECK=content
git:
    depth: false # to get blame information for SonarCloud
addons:
  sonarcloud:
# See https://docs.travis-ci.com/user/sonarcloud/
    organization: "i2pc"
    token:
        secure: $SONAR_TOKEN

cache: ccache

before_install:
 - sudo apt-get install -y libfftw3-dev libopenmpi-dev openmpi-bin libhdf5-dev python-numpy
script:
 - |
     python ./scripts/travis_before_script.py && \
     ./xmipp && \
     ccache -s
     #build-wrapper-linux-x86-64 --out-dir bw-outputs ./xmipp && \
     #sonar-scanner
